services:
  db:
    image: postgres
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data 
    networks:
      - app_network

  web:
    build: .
    command: >
      sh -c "sleep 10 && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - app_network
  
  cron:
    build: .
    command: sh -c "sleep 10 && crontab /app/crontab && cron -f"
    volumes:
      - .:/app
      - ./crontab:/app/crontab 
    depends_on:
      - db
      - web
    env_file:
      - .env
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge