# Generated by Django 4.1.13 on 2025-03-04 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_event_total_tickets_ticket_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='expires_at',
            field=models.DateTimeField(default='2025-03-02 10:00:00'),
            preserve_default=False,
        ),
    ]
