# Generated by Django 4.1.13 on 2025-03-05 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_event_currency_event_ticket_price_order_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='currency',
        ),
    ]
