# Generated by Django 4.1.13 on 2025-03-05 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_remove_order_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
